#![allow(non_camel_case_types, dead_code)]

#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ArmInsn {
    ARM_INS_INVALID = 0,
    ARM_INS_ADC,
    ARM_INS_ADD,
    ARM_INS_ADR,
    ARM_INS_AND,
    ARM_INS_ASR,
    ARM_INS_B,
    ARM_INS_BIC,
    ARM_INS_BKPT,
    ARM_INS_BL,
    ARM_INS_BLX,
    ARM_INS_BX,
    ARM_INS_CBNZ,
    ARM_INS_CBZ,
    ARM_INS_CMN,
    ARM_INS_CMP,
    ARM_INS_EOR,
    ARM_INS_HINT,
    ARM_INS_IT,
    ARM_INS_LDM,
    ARM_INS_LDR,
    ARM_INS_LDRB,
    ARM_INS_LDRH,
    ARM_INS_LDRSB,
    ARM_INS_LDRSH,
    ARM_INS_LSL,
    ARM_INS_LSR,
    ARM_INS_MLS,
    ARM_INS_MOV,
    ARM_INS_MOVS,
    ARM_INS_MUL,
    ARM_INS_MVN,
    ARM_INS_NOP,
    ARM_INS_ORN,
    ARM_INS_ORR,
    ARM_INS_POP,
    ARM_INS_PUSH,
    ARM_INS_ROR,
    ARM_INS_RRX,
    ARM_INS_RSB,
    ARM_INS_SBC,
    ARM_INS_STM,
    ARM_INS_STR,
    ARM_INS_STRB,
    ARM_INS_STRH,
    ARM_INS_SUB,
    ARM_INS_TEQ,
    ARM_INS_TST,
    ARM_INS_UBFX,
    ARM_INS_UDIV,
    ARM_INS_UXTB,
    ARM_INS_UXTH,
}

impl ArmInsn {
    pub fn from_raw(raw: u32) -> Option<Self> {
        Some(match raw {
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_INVALID as u32 => Self::ARM_INS_INVALID,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_ADC as u32 => Self::ARM_INS_ADC,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_ADD as u32 => Self::ARM_INS_ADD,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_ADR as u32 => Self::ARM_INS_ADR,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_AND as u32 => Self::ARM_INS_AND,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_ASR as u32 => Self::ARM_INS_ASR,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_B as u32 => Self::ARM_INS_B,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_BIC as u32 => Self::ARM_INS_BIC,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_BKPT as u32 => Self::ARM_INS_BKPT,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_BL as u32 => Self::ARM_INS_BL,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_BLX as u32 => Self::ARM_INS_BLX,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_BX as u32 => Self::ARM_INS_BX,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_CBNZ as u32 => Self::ARM_INS_CBNZ,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_CBZ as u32 => Self::ARM_INS_CBZ,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_CMN as u32 => Self::ARM_INS_CMN,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_CMP as u32 => Self::ARM_INS_CMP,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_EOR as u32 => Self::ARM_INS_EOR,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_HINT as u32 => Self::ARM_INS_HINT,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_IT as u32 => Self::ARM_INS_IT,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_LDM as u32 => Self::ARM_INS_LDM,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_LDR as u32 => Self::ARM_INS_LDR,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_LDRB as u32 => Self::ARM_INS_LDRB,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_LDRH as u32 => Self::ARM_INS_LDRH,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_LDRSB as u32 => Self::ARM_INS_LDRSB,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_LDRSH as u32 => Self::ARM_INS_LDRSH,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_LSL as u32 => Self::ARM_INS_LSL,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_LSR as u32 => Self::ARM_INS_LSR,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_MLS as u32 => Self::ARM_INS_MLS,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_MOV as u32 => Self::ARM_INS_MOV,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_MOVS as u32 => Self::ARM_INS_MOVS,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_MUL as u32 => Self::ARM_INS_MUL,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_MVN as u32 => Self::ARM_INS_MVN,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_NOP as u32 => Self::ARM_INS_NOP,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_ORN as u32 => Self::ARM_INS_ORN,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_ORR as u32 => Self::ARM_INS_ORR,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_POP as u32 => Self::ARM_INS_POP,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_PUSH as u32 => Self::ARM_INS_PUSH,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_ROR as u32 => Self::ARM_INS_ROR,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_RRX as u32 => Self::ARM_INS_RRX,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_RSB as u32 => Self::ARM_INS_RSB,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_SBC as u32 => Self::ARM_INS_SBC,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_STM as u32 => Self::ARM_INS_STM,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_STR as u32 => Self::ARM_INS_STR,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_STRB as u32 => Self::ARM_INS_STRB,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_STRH as u32 => Self::ARM_INS_STRH,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_SUB as u32 => Self::ARM_INS_SUB,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_TEQ as u32 => Self::ARM_INS_TEQ,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_TST as u32 => Self::ARM_INS_TST,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_UBFX as u32 => Self::ARM_INS_UBFX,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_UDIV as u32 => Self::ARM_INS_UDIV,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_UXTB as u32 => Self::ARM_INS_UXTB,
            x if x == capstone::arch::arm::ArmInsn::ARM_INS_UXTH as u32 => Self::ARM_INS_UXTH,
            _ => return None,
        })
    }
}

#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ArmCC {
    ARM_CC_EQ = 0,
    ARM_CC_NE,
    ARM_CC_HS,
    ARM_CC_LO,
    ARM_CC_MI,
    ARM_CC_PL,
    ARM_CC_VS,
    ARM_CC_VC,
    ARM_CC_HI,
    ARM_CC_LS,
    ARM_CC_GE,
    ARM_CC_LT,
    ARM_CC_GT,
    ARM_CC_LE,
    ARM_CC_AL,
}

impl ArmCC {
    pub fn from_u8(raw: u8) -> Self {
        match raw {
            x if x == Self::ARM_CC_EQ as u8 => Self::ARM_CC_EQ,
            x if x == Self::ARM_CC_NE as u8 => Self::ARM_CC_NE,
            x if x == Self::ARM_CC_HS as u8 => Self::ARM_CC_HS,
            x if x == Self::ARM_CC_LO as u8 => Self::ARM_CC_LO,
            x if x == Self::ARM_CC_MI as u8 => Self::ARM_CC_MI,
            x if x == Self::ARM_CC_PL as u8 => Self::ARM_CC_PL,
            x if x == Self::ARM_CC_VS as u8 => Self::ARM_CC_VS,
            x if x == Self::ARM_CC_VC as u8 => Self::ARM_CC_VC,
            x if x == Self::ARM_CC_HI as u8 => Self::ARM_CC_HI,
            x if x == Self::ARM_CC_LS as u8 => Self::ARM_CC_LS,
            x if x == Self::ARM_CC_GE as u8 => Self::ARM_CC_GE,
            x if x == Self::ARM_CC_LT as u8 => Self::ARM_CC_LT,
            x if x == Self::ARM_CC_GT as u8 => Self::ARM_CC_GT,
            x if x == Self::ARM_CC_LE as u8 => Self::ARM_CC_LE,
            _ => Self::ARM_CC_AL,
        }
    }
}